@startuml
class 남자친구{
기념일챙기기()
데이트하기()
}
class 아들{
효도하기()
안마하기()
}
class 직원(){
출근하기()
일하기()
}
class 군인(){
사격하기()
구보하기()
}

class 남자 {
기념일챙기기()
효도하기()
데이트하기()
안마하기()
출근하기()
일하기()
사격하기()
구보하기()
}
@enduml