@startuml
class 사람 {
    나이
    몸무게
    키
    혈액형
    직업
    연봉

    먹다()
    자다()
    울다()
    방귀 뀌다()
    싸다()
    일하다()
    운전하다()
    입금하다()
    출금하다()
    이체하다()
    대출하다()
    운동하다()
}
class 은행고객 {
    나이
    직업
    연봉

    입금하다()
    출금하다()
    이체하다()
    대출하다()
}
class 환자 {
    나이
    몸무게
    키
    혈액형

    먹다()
    자다()
    방귀 뀌다()
    싸다()
    운동하다()
}
@enduml